#!/usr/bin/env node

var exec    = require('child_process').exec;
var os      = require('os').type().toLowerCase();

// Run the test cases
console.log('Running test cases...');
exec('vows ' + __dirname + '/ioc.js --spec', function onVows(err, stdout, stderr) {
    if (!err) {
        console.log(stdout);
    } else {
        console.log(stderr);
    }

    // Clean up the fixtures
    if ('linux' === os || 'darwin' === os) {
        console.log('Cleaning up fixtures...');
        exec('rm -fr ' + __dirname + '/fixture/node_modules/norris-ioc', function() {
            console.log('Done! :D');
        });
    }    
});

